conf/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
	url(r'^admin/', admin.site.urls),

	url(r'^', include("main.urls")),
	url(r'^news/', include("news.urls")),
	url(r'^filials/', include("filials.urls")),
	url(r'^gallery/', include("gallery.urls")),
	url(r'^about/', include("about.urls")),
	url(r'^new-student/', include("new_student.urls")),
	url(r'^subscribe/', include("subscribers.urls")),
	url(r'^academy/', include("academy.urls")),
	url(r'^encyclopedia/', include("encyclopedia.urls")),
	url(r'^search/', include("search.urls")),
]

handler404 = 'main.views.page_404'
handler500 = 'main.views.page_500'

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modules/about/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import about_page

urlpatterns = [
	url(r'^$', about_page, name='about'),
]

modules/master/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import masters_page, master_article

urlpatterns = [
	url(r'^$', masters_page, name="masters"),
	url(r'^(?P<pk>[0-9]+)/$', master_article, name="master"),
]

modules/news/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import news_list, new_detail

urlpatterns = [
	url(r'^$', news_list, name='news_list'),
	url(r'^(?P<slug>[a-z0-9-_]+)/$', new_detail, name="new_detail"),
]

modules/about/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.db.models import Q
from search.models import SearchManager


def get_uploaded_file_name(instance, filename):
	return "images/about/%s" % filename


class AboutManager(SearchManager):
	def get_search_qs(self, q):
		return self.get_queryset().filter(
			Q(title__icontains=q) | Q(text__icontains=q)
		).distinct()


class About(models.Model):
	title = models.CharField(u"Заголовок", max_length=100)
	text = models.TextField(u"Текст", blank=True, null=True)
	img = models.ImageField(u"Картинка", upload_to=get_uploaded_file_name,
	                        blank=True, null=True)
	updated = models.DateTimeField(u"Данные обновлены", auto_now=True,
	                               auto_now_add=False)
	created = models.DateTimeField(u"Данные созданы", auto_now=False,
	                               auto_now_add=True)

	objects = AboutManager()

	@property
	def data_for_search(self):
		return {
			'title': self.title,
			'url_name': 'about'
		}

	class Meta:
		verbose_name = u'О школе'
		verbose_name_plural = u'О школе'

modules/academy/models.py
# -*- coding: utf-8 -*-

from django.db import models


def get_uploaded_file_name(instance, filename):
	return "images/academy/%s" % filename

class Academy(models.Model):
	title = models.CharField(u"Заголовок", max_length=400)
	description = models.TextField(u"Описание", blank=True, null=True)
	ref_video = models.CharField(u"Видео", max_length=400, blank=True,
	                             null=True)
	updated = models.DateTimeField(u"Данные обновлены", auto_now=True,
	                               auto_now_add=False)
	created = models.DateTimeField(u"Данные созданы", auto_now=False,
	                               auto_now_add=True)

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = u'Академия'
		verbose_name_plural = u'Академия'

class Section(models.Model):
	title = models.CharField(u"Название раздела", max_length=400)
	description = models.TextField(u"Описание", blank=True, null=True)
	img = models.ImageField(upload_to=get_uploaded_file_name,
	                        verbose_name=u"Картинка", blank=True, null=True)
	updated = models.DateTimeField(u"Данные обновлены", auto_now=True,
	                               auto_now_add=False)
	created = models.DateTimeField(u"Данные созданы", auto_now=False,
	                               auto_now_add=True)

	class Meta:
		ordering = ['created']

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = u'Раздел академии'
		verbose_name_plural = u'Раздел академии'

class Subsection(models.Model):
	title = models.CharField(u"Название подраздела", max_length=400)
	section = models.ForeignKey(Section, verbose_name=u"Раздел")
	updated = models.DateTimeField(u"Данные обновлены", auto_now=True,
	                               auto_now_add=False)
	created = models.DateTimeField(u"Данные созданы", auto_now=False,
	                               auto_now_add=True)

	class Meta:
		ordering = ['created']

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = u'Подраздел академии'
		verbose_name_plural = u'Подраздел академии'

class Video(models.Model):
	title = models.CharField(u"Название видео", max_length=400)
	ref_video = models.CharField(u"Ссылка на видео", max_length=400)
	subsection = models.ForeignKey(Subsection, verbose_name=u"Подраздел")
	updated = models.DateTimeField(u"Данные обновлены", auto_now=True,
	                               auto_now_add=False)
	created = models.DateTimeField(u"Данные созданы", auto_now=False,
	                               auto_now_add=True)

	class Meta:
		ordering = ['created']

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = u'Видео'
		verbose_name_plural = u'Видео'

modules/filials/models.py
# -*- coding: utf-8 -*-

from django.db import models

from trainers.models import Trainer


class Filial(models.Model):
	CITIES = (
		('Rostov', u'Ростов-на-Дону'),
		('Cimlyansk', u'Цимлянск'),
		('Shahty', u'Шахты'),
	)
	city = models.CharField(u"Город", max_length=300, choices=CITIES,
	                        default='Rostov')
	address = models.CharField(u"Адрес", max_length=300, blank=True, null=True)
	map_coord_x = models.FloatField(u"Координата х на карте", blank=True,
	                                null=True)
	map_coord_y = models.FloatField(u"Координата у на карте", blank=True,
	                                null=True)
	email = models.CharField(u"E-mail", max_length=300, blank=True,
	                         null=True)
	phone = models.CharField(u"Телефон", max_length=300)
	timetable_adults = models.TextField(u"Расписание (взрослые)", blank=True,
	                                    null=True)
	timetable_children = models.TextField(u"Расписание (дети)", blank=True,
	                                      null=True)
	trainer = models.ManyToManyField(Trainer, verbose_name=u"Тренер",
	                                 related_name="filial",
	                                 related_query_name="filial", blank=True)
	updated = models.DateTimeField(u"Данные обновлены", auto_now=True,
	                               auto_now_add=False)
	created = models.DateTimeField(u"Данные созданы", auto_now=False,
	                               auto_now_add=True)

	class Meta:
		ordering = ['id',]

	def __unicode__(self):
		return self.city

	def __str__(self):
		return self.city

	class Meta:
		verbose_name = u'Филиал'
		verbose_name_plural = u'Филиалы'

modules/gallery/models.py
# -*- coding: utf-8 -*-

from transliterate import translit, detect_language

from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from django.utils.text import slugify

from search.models import SearchManager


def get_uploaded_file_name(instance, filename):
	return "gallery/%s" % filename

class Category(models.Model):
	title = models.CharField(u"Название категории", max_length=400)

	class Meta:
		ordering = ['title',]

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = u'Тип альбомов'
		verbose_name_plural = u'Тип альбомов'


class AlbumManager(SearchManager):
	def get_search_qs(self, q):
		return self.get_queryset().filter(
			Q(title__icontains=q) |
			Q(description__icontains=q)
		).distinct()


class Album(models.Model):
	title = models.CharField(u"Название альбома", max_length=400)
	slug = models.SlugField(unique=True, blank=True, null=True)
	cover = models.ImageField(u"Обложка", upload_to=get_uploaded_file_name,
	                          blank=True, null=True)
	description = models.TextField(u"Описание альбома", blank=True, null=True)
	category = models.ForeignKey(Category)
	updated = models.DateTimeField(u"Данные обновлены", auto_now=True,
	                               auto_now_add=False)
	created = models.DateTimeField(u"Данные созданы", auto_now=False,
	                               auto_now_add=True)

	objects = AlbumManager()

	class Meta:
		ordering = ['updated', 'created']

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	@models.permalink
	def get_absolute_url(self):
		return ('album_detail', None, {'symbol_code': self.slug})

	@property
	def data_for_search(self):
		return {
			'title': self.title,
			'text': self.description,
			'href': self.get_absolute_url()
		}

	class Meta:
		verbose_name = u'Альбом'
		verbose_name_plural = u'Альбомы'

class Photo(models.Model):
	title = models.CharField(u"Заголовок фото", max_length=400, blank=True,
	                         null=True)
	comment = models.TextField(u"Комментарий к фотографии", blank=True,
	                           null=True)
	img = models.ImageField(u"Картинка", upload_to=get_uploaded_file_name)
	album = models.ForeignKey(Album)
	updated = models.DateTimeField(u"Данные обновлены", auto_now=True,
	                               auto_now_add=False)
	created = models.DateTimeField(u"Данные созданы", auto_now=False,
	                               auto_now_add=True)

	class Meta:
		ordering = ['updated', 'created']

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	@models.permalink
	def get_absolute_url(self):
		return ('photoy_detail', None, {'symbol_code': self.slug})

	class Meta:
		verbose_name = u'Фото'
		verbose_name_plural = u'Фото'

def pre_save_post(sender, instance, *args, **kwargs):
	if instance.slug:
		slug_init = instance.slug
	else:
		if detect_language(instance.title) == 'ru':
			slug_init = slugify(translit(instance.title, reversed=True))
		else:
			slug_init = slugify(instance.title)

	slug = slug_init
	exists = sender.objects.filter(slug=slug).exclude(id=instance.id).exists()
	i = 0
	while exists:
		i += 1;
		slug = "%s-%s" % (slug_init, i)
		exists = sender.objects.filter(slug=slug).exists()
	instance.slug = slug

pre_save.connect(pre_save_post, sender=Album)

modules/news/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import New

class NewForm(forms.ModelForm):
	class Meta:
		model = New
		fields = ['title', 'preview_text', 'detail_text']

modules/about/views.py
# -*- coding: utf-8 -*-

from django.views.generic.base import TemplateView

from main.helpers import get_random_citation
from trainers.models import Trainer
from .models import About

class AboutPageView(TemplateView):
	template_name = "pages/about.html"

	def get_context_data(self, **kwargs):
		context = super(AboutPageView, self).get_context_data()
		context.update(get_random_citation())
		context.update({
			'data' : About.objects.filter().first(),
			'trainers': Trainer.objects.filter(),
		})
		return context

about_page = AboutPageView.as_view()

modules/academy/views.py
# -*- coding: utf-8 -*-

from django.views.generic.base import TemplateView

from citations.models import Citation
from .models import Academy, Section

class AcademyPageView(TemplateView):
	template_name = "pages/academy.html"

	def get_context_data(self, **kwargs):
		context = super(AcademyPageView, self).get_context_data()
		context.update({
			'sections' : Section.objects.filter(),
			'academy' : Academy.objects.filter().first(),
			'citation' : Citation.objects.values('master__apelido', 'master__name', 'text').order_by('?').first(),
		})
		return context

academy_page = AcademyPageView.as_view()

modules/encyclopedia/views.py
# -*- coding: utf-8 -*-

from django.views.generic.base import TemplateView


class EncyclopediaPageView(TemplateView):
	template_name = "pages/encyclopedia.html"
	url_name_article = "encyclopedia"


encyclopedia_page = EncyclopediaPageView.as_view()

modules/filials/views.py
# -*- coding: utf-8 -*-

from django.views.generic.base import TemplateView

from .models import Filial


class FilialsPageView(TemplateView):
	template_name = "pages/filials.html"

	def get_context_data(self, **kwargs):
		context = super(FilialsPageView, self).get_context_data()
		context.update({
			'filials' : Filial.objects.filter().order_by('id', 'city')
		})
		return context

filials_page = FilialsPageView.as_view()

modules/gallery/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.base import TemplateView

from .models import Album, Photo


class GalleryPageView(TemplateView):
	template_name = "pages/gallery.html"

	def get_context_data(self, **kwargs):
		context = super(GalleryPageView, self).get_context_data()

		albums = Album.objects.filter()
		categories = {}
		for album in albums:
			categories.setdefault(album.category.title, [])
			categories[album.category.title].append(album)

		context.update({
			'categories' : categories
		})
		return context

gallery_page = GalleryPageView.as_view()


class AlbumPageView(TemplateView):
	template_name = "pages/album.html"

	def get_context_data(self, **kwargs):
		context = super(AlbumPageView, self).get_context_data()

		album = get_object_or_404(Album, slug=kwargs.get('symbol_code'))
		query_list = Photo.objects.filter(album=album.id)

		paginator = Paginator(query_list, 16)
		page = self.request.GET.get('page')
		try:
			photos = paginator.page(page)
		except PageNotAnInteger:
			photos = paginator.page(1)
		except EmptyPage:
			photos = paginator.page(paginator.num_pages)

		context.update({
			'album': album,
			'photos' : photos,
			'page_var': 'page',
			'paginator': paginator,
		})
		return context

album_page = AlbumPageView.as_view()

modules/master/views.py
# -*- coding: utf-8 -*-

from django.views.generic import DetailView
from django.views.generic import ListView

from master.models import Master
from main.helpers import get_random_citation


class MastersPageView(ListView):
	model = Master
	template_name = "pages/masters.html"
	context_object_name = "masters"

	def get_context_data(self, **kwargs):
		context = super(MastersPageView, self).get_context_data(**kwargs)
		context.update(get_random_citation())
		return context

masters_page = MastersPageView.as_view()


class MasterArticleView(DetailView):
	model = Master
	template_name = "pages/master.html"
	context_object_name = "master"

	def get_context_data(self, **kwargs):
		context = super(MasterArticleView, self).get_context_data(**kwargs)
		context.update(get_random_citation())
		context.update({
			'other_masters': Master.objects.exclude(id=self.object.id)[:4]
		})
		return context


master_article = MasterArticleView.as_view()

modules/news/views.py
# -*- coding: utf-8 -*-

from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from main.helpers import get_random_citation
from .models import New

class NewListView(ListView):
	model = New
	template_name = 'pages/news.html'
	paginate_by = 5
	context_object_name = 'news'

	def get_context_data(self, **kwargs):
		context = super(NewListView, self).get_context_data()
		context.update(get_random_citation())
		return context


news_list = NewListView.as_view()


class NewDetailView(DetailView):
	model = New
	template_name = 'pages/new.html'

	def get_context_data(self, **kwargs):
		context = super(NewDetailView, self).get_context_data()
		context.update(get_random_citation())
		return context

new_detail = NewDetailView.as_view()

templates/pages/academy.html
{% extends "base.html" %}

{% block meta_description %}
	Обучение капоэйре онлайн в академии Capoeira de Rua. Базовые техника, ритмы и танцы в капоэйре
{% endblock %}

{% block meta_keywords %}
	капоэйра онлайн, базовая техника капоэйры, уроки по капоэйре, музыка в капоэйре, бразильская самба, capoeira de rua
{% endblock %}

{% load staticfiles %}

{% block title %}
	Академия школы капоэйры Capoeira de Rua
{% endblock title %}

{% block content %}
	<!-- Start Page Banner -->
	<div class="page-banner">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<ul class="breadcrumbs">
						<li><a href="#">Главная</a></li>
						<li>Академия</li>
					</ul>
				</div>
				<div class="col-md-6">
					<div class="navbar-title">
					<h1> АКАДЕМИЯ <p>школы Capoeira de Rua</p></h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Page Banner -->

	<!-- Start Content -->
	<div id="content">
		<div class="container">
			<div class="row sidebar-page">

				<div class="col-md-9 page-content">
					<div class="row">
						<div class="col-md-12">
							<span class="h4 classic-title"><span>{{ academy.title }}</span>
							<p>{{ academy.description |safe }}</p>
						</div>
					</div>


					<div class="tabs-section">
						<!-- Nav Tabs -->
						<ul class="nav nav-tabs">
							{% for section in sections%}
								<li class="{% if section.id == 1 %}active{% endif %}"><a href="#tab-{{ section.id }}" data-map-id="{{ section.id }}" data-toggle="tab">{{ section.title }}</a></li>
							{% endfor %}
						</ul>

						<!-- Tab Panels -->
						<div class="tab-content">
						{% for section in sections%}
							<div class="tab-pane fade {% if section.id == 1 %}in active{% endif %}" id="tab-{{ section.id }}">
								<div class="row">
									<div class="col-md-12">
										<div class="col-md-4">
											<!-- Accordion -->
											<div class="panel-group" id="accordion">
											{% for subsection in section.subsection_set.all %}

												<div class="panel-default">
													<!-- Toggle Heading -->
													<div class="panel-heading">
														<span class="h4 panel-title">
															<a data-toggle="collapse" data-parent="#accordion" href="#collapse-{{ subsection.id }}">
																<i class="fa fa-angle-up control-icon"></i>
																{{ subsection.title }}
															</a>
														</h4>
													</div>
													<!-- Toggle Content -->
													<div id="collapse-{{ subsection.id }}" class="panel-collapse collapse in">
														<div class="panel-body">
															<ul>
																{% for video in subsection.video_set.all %}
																	<li>
                                                                        <a class="show-video" target="_blank" data-video-id="{{ video.id }}">
																			{{ video.title }}
																		</a>
                                                                    </li>
																{% endfor %}
															</ul>
														</div>
													</div>
												</div>
											{% endfor %}
											</div>
											<!-- End Accordion -->
										</div>

										<div class="col-md-8 text-center">
											<img src="{{ section.img.url }}" title="{{ section.description }}" alt="{{ section.title }}">
										</div>
									</div><!-- col-md-12 -->
								</div><!-- row -->
							</div><!-- tab-pane -->
						{% endfor %}
						</div>
						<!-- End Tab Panels -->

					</div>
					<!-- tabs-section -->

				</div>
				<!-- End Page Content -->


				<!--Sidebar-->
				<div class="col-md-3 sidebar right-sidebar">
					{% include "components/come-to-us.html" %}
				
					<!-- Start Post -->
					<div class="blog-post quote-post">
						<div class="qoute-box">
							<a href="#">
								<span class="h2">"{{ citation.text }}"</span>
								<div class="qoute-author">Местре 
									{%if citation.master__apelido %}
										{{ citation.master__apelido }}
											{% else %}
										{{citation.master__name }}
									{% endif %}
								</div>
							</a>
						</div>
					</div>
					<!-- End Post -->

					{% include "components/tags.html" %}

				</div>
				<!--End sidebar-->

			</div>
			<!--End sidebar-page-->

		</div>
		<!--End container-->

	</div>
	<!-- End Content -->
{% endblock content %}

templates/pages/filials.html
{% extends "base.html" %}

{% block meta_description %}
	Филиалы школы капоэйры Capoeira de Rua. Запишитесь на занятие по капоэйре. Тел: 8(988)890-36-05
{% endblock %}

{% block meta_keywords %}
	расписание в школе капоэйры, адрес школы капоэйры, филиалы школы капоэйры, инструктора школы капоэйры, monitor abelha
{% endblock %}

{% load staticfiles %}

{% block title %}
	Филиалы школы капоэйры Capoeira de Rua
{% endblock title %}

{% block content %}
	<script src="http://maps.google.ru/maps/api/js?v=3&sensor=false" type="text/javascript"></script>
	<script type="text/javascript" src="{% static 'js/maps.min.js' %}"></script>
	<!-- Start Page Banner -->
	<div class="page-banner">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<ul class="breadcrumbs">
						<li><a href="#">Главная</a></li>
						<li>Филиалы</li>
					</ul>
				</div>
				<div class="col-md-6">
					<div class="navbar-title">
					<h1> ФИЛИАЛЫ <p>школы Capoeira de Rua</p></h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Page Banner -->

	<!-- Start Content -->
	<div id="content">
		<div class="container">
			<div class="row sidebar-page">

				<div class="col-md-9 page-content">
					<div class="tabs-section">

						<!-- Nav Tabs -->
						<ul class="nav nav-tabs">
							{% for filial in filials %}
								<li class="{% if filial.id == 1 %}active{% endif %}"><a href="#tab-{{ filial.id }}" data-map-id="{{ filial.id }}" data-toggle="tab">{{ filial.get_city_display }}</a></li>
							{% endfor %}
						</ul>

						<!-- Tab Panels -->
						<div class="tab-content">
						{% for filial in filials %}
							<!-- Tab Content {{ filial.id }} -->
							<div class="tab-pane fade {% if filial.id == 1 %}in active{% endif %}" id="tab-{{ filial.id }}">
								<div class="row">
									<div id="map-{{ filial.id }}" class="map"  style="width: 100%; height: 350px;"
										data-position-latitude="{{ filial.map_coord_x }}"
										data-position-longitude="{{ filial.map_coord_y }}"
										data-marker-img="{% static 'images/metka.png' %}"
										data-marker-title="{{ filial.address }}"
									></div>
								</div>

								<br>

								<div class="row">
									<div class="col-md-5">
										<!-- Classic Heading -->
										<p><span class="h4 classic-title">Контакты</span></p>

										<!-- Info - Icons List -->
										<ul class="icons-list">
											<li><i class="fa fa-globe"></i> <strong>Адресс:</strong> {{ filial.address }}</li>
											<li><i class="fa fa-envelope-o"></i> <strong>E-mail:</strong> <a href="mailto:{{ filial.email }}">{{ filial.email }}</a></li>
											<li><i class="fa fa-mobile"></i> <strong>Телефон:</strong> {{ filial.phone }}</li>
										</ul>
									</div>

									<div class="col-md-4">
										<p><span class="h4 classic-title">Расписание (взрослые)</span></p>
										{% if filial.timetable_adults %}
											{{ filial.timetable_adults|safe }}
										{% else %}
											<p>
												Расписание пока не добавили на сайт. Не расстраивайтесь, тренер точно вам подскажет: {{ filial.phone }}
											</p>
										{% endif %}
									</div>

									<div class="col-md-3">
										<p><span class="h4 classic-title">Расписание (дети)</span></p>
										{% if filial.timetable_children %}
											{{ filial.timetable_children|safe }}
										{% else %}
											<p>Детской группы пока нет</p>
										{% endif %}
									</div>
								</div><!-- row -->

								<br>

								<div class="row">
									<div class="col-md-12">
										<!-- Divider -->
										<div class="hr1" style="margin-bottom:10px;"></div>

										<!-- Classic Heading -->
										<p><span class="h4 classic-title">Инструкторы</span></p>

										{% for trainer in filial.trainer.all %}
											<!-- Start Toggle {{ trainer.id }} -->
											<div class="col-md-6">
												<div class="photo-in-list">
													{% if trainer.photo %}
													<a class="fancybox" title="{{ trainer.status }}" href="{{ trainer.photo.url }}">
														<img alt="{{ trainer.status }} {{ trainer}}" src="{{ trainer.photo.url }}" />
													</a>
													{% else %}
														<img alt="{{ trainer.status }} {{ trainer}}" src="{% static 'images/cap.png' %}" />
													{% endif %}
												</div>
												<div class="text-center">
													<a data-toggle="collapse" data-parent="#toggle" href="#collapse-{{ trainer.id }}" aria-expanded="false" class="collapsed">
														<span class="h4 accent-color">{% if trainer.apelido %}{{ trainer.apelido }} {% else %} {{ trainer.name }}{% endif %}</span>
													</a>
												</div>
												<div id="collapse-{{ trainer.id }}" class="panel-collapse collapse" aria-expanded="false">
													<div class="panel-body">
														<span class="h5">{% if trainer.status %}{{ trainer.status }} {% endif %}</span>
														<p>{{ trainer.biography }}</p>
													</div>
												</div>
											</div>
										{% endfor %}
									</div>
								</div>
							</div>
						{% endfor %}
						</div>
						<!-- End Tab Panels -->

					</div>
					<!-- tabs-section -->

				</div>
				<!-- End Page Content -->


				<!--Sidebar-->
				<div class="col-md-3 sidebar right-sidebar">
					{% include "components/come-to-us.html" %}

					{% include "components/tags.html" %}
				</div>
				<!--End sidebar-->

			</div>
			<!--End sidebar-page-->

		</div>
		<!--End container-->

	</div>
	<!-- End Content -->
{% endblock content %}