conf/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
	url(r'^admin/', admin.site.urls),

	url(r'^', include("main.urls")),
	url(r'^news/', include("news.urls")),
	url(r'^filials/', include("filials.urls")),
	url(r'^gallery/', include("gallery.urls")),
	url(r'^about/', include("about.urls")),
	url(r'^new-student/', include("new_student.urls")),
	url(r'^subscribe/', include("subscribers.urls")),
	url(r'^academy/', include("academy.urls")),
	url(r'^encyclopedia/', include("encyclopedia.urls")),
	url(r'^search/', include("search.urls")),
]

handler404 = 'main.views.page_404'
handler500 = 'main.views.page_500'

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modules/new_student/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import add_student,	new_student_form

urlpatterns = [
	url(r'^form/$', new_student_form),
	url(r'^add/$', add_student),
]

modules/new_student/models.py
# -*- coding: utf-8 -*-

from django.db import models

from filials.models import Filial


class NewStudent(models.Model):
	name = models.CharField(u"ФИО", max_length=400)
	phone = models.CharField(u"Номер телефона", max_length=400)
	filial = models.ForeignKey(Filial, verbose_name=u"Филиал")
	updated = models.DateTimeField(u"Данные обновлены", auto_now=True,
	                               auto_now_add=False)
	created = models.DateTimeField(u"Данные созданы", auto_now=False,
	                               auto_now_add=True)

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = u'Запись нового ученика'
		verbose_name_plural = u'Записи новых учеников'

modules/new_student/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import NewStudent


class NewStudentForm(forms.ModelForm):
	class Meta:
		model = NewStudent
		fields = ['name', 'phone', 'filial']

modules/new_student/views.py
# -*- coding: utf-8 -*-

import json

from django.contrib.sites.shortcuts import get_current_site
from django.core.context_processors import csrf
from django.http.response import HttpResponse
from django.shortcuts import render_to_response
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from filials.models import Filial
from main.helpers import added_new_student

from .forms import NewStudentForm
from .models import NewStudent


def add_student(request):
	if request.method == 'POST':
		form_student = NewStudentForm(request.POST)
		if form_student.is_valid():
			student = form_student.save()

			#send message admin
			current_site = get_current_site(request)
			added_new_student(student.name, student.phone, student.filial.get_city_display(),
			                  current_site.domain)
			return render_to_response('forms/success_add_student.html', {'name' : student.name})
		else:
			return HttpResponse(
				json.dumps({
					u'error': u'Проверьте корректность введенных данных'
				}),
				content_type='application/json'
			)


class NewStudentFormView(FormView):
	form_class = NewStudentForm
	template_name = "forms/new_student.html"

	def get_context_data(self, **kwargs):
		context = super(NewStudentFormView, self).get_context_data()
		context.update({
			"filials": Filial.objects.filter()
		})
		return context


new_student_form = NewStudentFormView.as_view()

templates/forms/new_student.html
{% load staticfiles %}
<div class="container-form">
	<div class="margin-bottom-20">
		<span class="h4 big-title">Запишитесь на занятие</span>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
	</div>
	<div class="errors">
	</div>
	<form action="/new-student/form/" method="post" enctype="multipart/form-data" id="form-register-class" class="contact-form">
		{% csrf_token %}
		<div class="form-group">
			<div class="controls">
				<input id="id_name" placeholder="ФИО" name="name" type="text">
			</div>
		</div>
		<div class="form-group">
			<div class="controls">
				<input id="id_phone" placeholder="Номер телефона" name="phone" type="text">
			</div>
		</div>
		<div class="form-group">
			<div class="controls">
				<select id="id_filial" name="filial" placeholder="Филиал">
					{% for filial in filials %}
						<option value="{{ filial.id }}">{{ filial.get_city_display }}</option>
					{% endfor %}
				</select>
			</div>
		</div>		
		
		<input type="submit" class="btn-system btn-large" value="Записаться">
	</form>
</div>

<script type="text/javascript" src="{% static 'js/forms.min.js' %}"></script>

templates/forms/success_add_student.html
{% load staticfiles %}
<div class="container-form">
	<div class="margin-bottom-20">
		<span class="h4 big-title">{{ name }}, ждем Вас на <a href="/filials/">ближайшем классе</a> по капоэйре</span>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
	</div>
	<div>
		<div class="hr5 margin-vert-20"></div>
		<p>C собой иметь удобную спортивную форму и хорошее натроение :-)</p>
		<img src="{% static 'images/we-wait-you.jpg' %}">
	<div>
</div>